# CommandShortcuts - Configuration file

# # # # # # # # # # # # # # # # # # # # #
# 
#    General configuration
#
# # # # # # #

# Effect GUID used to signal the validation of a hotkey
ValidatedEffectGUID: bc41e0feaebe4e788a3612811b8722d3

# Icon displayed when a message is sent by the plugin
ChatIcon: https://i.imgur.com/nD9DLyu.png
#
# # #

# # # # # # # # # # # # # # # # # # # # #
# 
#    Shortcut commands
#
# # # # # # #
Shortcuts:

  # Permission needed to use the shortcut
- Permission: cmdsc.healing.default

  # Command executed by the shortcut
  Command: /heal {PlayerID}

  ExecuteAsConsole: true

  # Command cooldown
  Cooldown: 3600

  # Shortcut keys
  #   Available keys : [None, Jump, Primary, Secondary, Crouch, Prone, Sprint, LeanLeft, LeanRight, ToggleTactical, HoldBreath, Plugin1, Plugin2, Plugin3, Plugin4, Plugin5]
  Hotkeys:
  - Prone, LeanLeft
  - Prone
  - Prone, LeanRight

  # Hotkey casts
  Casts:
  - 2
  - 0
  - 2

- Permission: cmdsc.healing.vip
  Command: /heal {PlayerID}
  ExecuteAsConsole: true
  Cooldown: 600
  Hotkeys:
  - Plugin1
#
# # #