# CommandHotkeys - Configuration file

# # # # # # # # # # # # # # # # # # # # #
# 
#    Shortcut commands
#
# # # # # # #
Commands:

  # Permission needed to use the shortcut
- Permission: cmdsc.healing.default

  # Command executed by the shortcut
  Command: /heal

  ExecuteAsConsole: true

  # Command cooldown
  Cooldown: 3600

  # Shortcut keys
  #   Available keys : [None, Jump, Primary, Secondary, Crouch, Prone, Sprint, LeanLeft, LeanRight, ToggleTactical, HoldBreath, Plugin1, Plugin2, Plugin3, Plugin4, Plugin5]
  Hotkeys:
  - Sprint, LeanLeft
  - None
  - Sprint, LeanRight

  # Hotkey casts
  Casts:
  - 2
  - 0
  - 2

- Permission: cmdsc.healing.vip
  Command: /heal
  ExecuteAsConsole: true
  Cooldown: 600
  Hotkeys:
  - Plugin1